# Generated by Django 4.2.1 on 2023-06-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
